#! /usr/bin/env python
# encoding: utf-8

import os, sys, subprocess


def options(opt):
    pass


def configure(conf):
    pass

def build(bld):
    bld.stlib(features  = 'c',
          source    = ['lib/Remotery.c'],
          includes  = ['lib'],
          export_includes = ['lib'],
          target    = 'remotery')
