#! /usr/bin/env python
# encoding: utf-8

import sys

def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld( export_includes    = '.',
         target             = 'greatest.h',
         name               = 'greatest')

