#! /usr/bin/env python
# encoding: utf-8

import os, sys, subprocess


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld.stlib(features  = 'cxx',
          source        = bld.path.ant_glob('source/voronoi/source/**/*.cpp'),
          includes      = 'source/voronoi/include',
          export_includes = 'source/voronoi/include',
          defines       = ['VORONOI_STATIC'],
          target        = 'voronoi')

