#! /usr/bin/env python
# encoding: utf-8

import os

def options(opt):
    pass


def configure(conf):
    conf.find_program('cmake')


def build(bld):
    projectdir = bld.path.abspath()
    installdir = bld.path.get_bld().abspath()
    libfile = os.path.join('glbinding', 'lib', 'libglbinding.a')
    includedir = os.path.join(installdir, 'include')
    
    bld(rule="cmake -DOPTION_BUILD_STATIC=ON -DCMAKE_INSTALL_PREFIX:PATH=%s %s && make && make install" % (installdir, projectdir),
        cwd=projectdir,
        target='libglbinding.a',
        export_includes=includedir,
        name="glbinding")
