#! /usr/bin/env python
# encoding: utf-8

import os, sys

def options(opt):
    pass


def configure(conf):
    pass

    
def build(bld):

    defines = ['GLBINDING_STATIC']
    if sys.platform == 'win32':
        defines += ['WIN32']
        
    bld(features="cxxstlib cxx",
        source=bld.path.ant_glob('source/glbinding/source/**/*.cpp'),
        includes='source/glbinding/include',
        export_includes='source/glbinding/include',
        defines=defines,
        target='glbinding')

    