#! /usr/bin/env python
# encoding: utf-8

import os, sys, subprocess


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    
    bld.stlib(features  = 'cxx',
          source    = ['imgui.cpp'],
          includes = '.',
          export_includes = ['.'],
          target    = 'imgui')

