#! /usr/bin/env python
# encoding: utf-8

import os, sys, subprocess


def options(opt):
    pass


def configure(conf):
    conf.find_program('git', var='GIT')


def build(bld):
    defines = []
    includes = []
    sourcedir = 'src/'
    sourcedirfiles = [x for x in os.listdir(sourcedir) if x.endswith('.c')]
    if sys.platform == 'linux2':
        platformfiles = [x for x in sourcedirfiles if x.startswith('x11') or x.startswith('xkb') or x.startswith('glx') or x.startswith('linux')]
        includes += ['/usr/include']
        defines = ['_GLFW_X11', '_GLFW_USE_OPENGL']
        
    elif sys.platform == 'darwin':
        sourcedirfiles += [x for x in os.listdir(sourcedir) if x.endswith('.m')]
        platformfiles = [x for x in sourcedirfiles if x.startswith('cocoa') or x.startswith('nsgl') or x.startswith('iokit') or x.startswith('mach')]
        defines = ['_GLFW_COCOA', '_GLFW_USE_OPENGL']
        
    elif sys.platform == 'win32':
        platformfiles = [x for x in sourcedirfiles if x.startswith('win32') or x.startswith('wgl') or x.startswith('winmm')]
        defines = ['_GLFW_WIN32', '_GLFW_USE_OPENGL', '_GLFW_WGL']
        
    commonfiles = ['context.c', 'init.c', 'input.c', 'monitor.c', 'window.c']
    glfwsource = [os.path.join(sourcedir, x) for x in commonfiles + platformfiles]
    
    glfw = bld.stlib(features  = 'c',
          source    = glfwsource,
          includes = ['include'] + includes,
          export_includes = ['include'],
          defines   = defines,
          target    = 'glfw')
    
    if sys.platform in ('linux2', 'darwin'):
        glfw.env.append_unique('CFLAGS', '-Wno-conversion')
        glfw.env.append_unique('CFLAGS', '-Wno-unused-parameter')
        glfw.env.append_unique('CFLAGS', '-Wno-sign-compare')
        glfw.env.append_unique('CFLAGS', '-Wno-deprecated-declarations')
        #conf.env['LIB_X11'] = ['X11', 'Xrandr', 'Xi', 'Xxf86vm']
    elif sys.platform == 'win32':
        glfw.env.append_unique('CFLAGS', '/wd4152')
        glfw.env.append_unique('CFLAGS', '/wd4244')
        glfw.env.append_unique('CFLAGS', '/wd4204')
        glfw.env.append_unique('CFLAGS', '/wd4306')
    if '-std=c++11' in glfw.env.CFLAGS:
        glfw.env.CFLAGS.remove('-std=c++11')

