#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    bld( features           = 'c cstlib',
         source             = bld.path.ant_glob('*.c'),
         includes           = '.',
         export_includes    = '.',
         target             = 'z',
         name               = 'zlib')
