#! /usr/bin/env python
# encoding: utf-8

import sys

def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    
    bld( features           = 'c cstlib',
         source             = bld.path.ant_glob('src/*.c'),
         includes           = 'include src/internal_includes',
         export_includes    = 'include',
         target             = 'hlsl')
