#! /usr/bin/env python
# encoding: utf-8

import sys

def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    
    defines = ['EXCLUDE_PSTDINT']
    if sys.platform == 'win32':
        defines = []
    
    bld( features           = 'c cstlib',
         source             = bld.path.ant_glob('src/**/*.c'),
         defines            = defines,
         includes           = 'include src src/cbstring',
         export_includes    = 'include',
         target             = 'hlslcc')
    
    bld( features           = 'cxx cxxprogram',
         source             = bld.path.ant_glob('offline/*.cpp') + bld.path.ant_glob('offline/cjson/*.c'),
         includes           = 'include offline offline/cjson',
         defines            = defines,
         use                = 'hlslcc',
         target             = 'HLSLcc')
