#! /usr/bin/env python
# encoding: utf-8

import sys

def options(opt):
    pass


def configure(conf):
    conf.env.LIB_gdi32 = ['gdi32']
    conf.env.LIB_user32 = ['user32']


def build(bld):
    
    defines = ['EXCLUDE_PSTDINT']
    libs = []
    if sys.platform == 'win32':
        defines = []
        libs = ['gdi32', 'user32']
    
    bld( features           = 'c cstlib',
         source             = bld.path.ant_glob('src/**/*.c'),
         defines            = defines,
         includes           = 'include src src/cbstring',
         export_includes    = 'include',
         target             = 'hlslcc')
    
    bld( features           = 'cxx cxxprogram',
         source             = bld.path.ant_glob('offline/*.cpp') + bld.path.ant_glob('offline/cjson/*.c'),
         includes           = 'include offline offline/cjson',
         defines            = defines,
         use                = ['hlslcc'] + libs,
         target             = 'HLSLcc')
