#! /usr/bin/env python
# encoding: utf-8

import os, sys, subprocess


def options(opt):
    pass


def configure(conf):
    pass


def build(bld):
    
    bld(features  = 'cxx',
        export_includes = ['include'],
        target    = 'rapidjson')
